
export const uiText = {
    fr: {
        title: "Planificateur de Découvertes",
        language: "Langue",
        topicLabel: "Que voulez-vous découvrir ?",
        topicPlaceholder: "Ex: Le mouvement Art Déco, la ville de Lyon...",
        seenLabel: "Lieux ou sujets déjà vus (optionnel)",
        seenPlaceholder: "Ex: La Tour Eiffel, le Louvre...",
        durationLabel: "Durée de la discussion",
        durationQuick: "Courte (~2 min)",
        durationMedium: "Moyenne (~4-5 min)",
        durationLong: "Longue (~8 min)",
        button: "Générer l'histoire",
        buttonLoading: "Génération...",
        welcomeMessage: "Racontez-moi ce que vous aimeriez explorer et je créerai une histoire pour votre voyage !",
        errorPrefix: "Une erreur est survenue: ",
        copy: "Copier",
        copied: "Copié !",
        playAudio: "Écouter",
        pauseAudio: "Pause",
        audioLoading: "Chargement...",
        audioErrorPrefix: "Erreur audio : ",
        download: "Télécharger",
        sourcesTitle: "Sources"
    },
    en: {
        title: "Holiday Discovery Helper",
        language: "Language",
        topicLabel: "What do you want to discover?",
        topicPlaceholder: "E.g.: The Art Deco movement, the city of Lyon...",
        seenLabel: "Places or topics already seen (optional)",
        seenPlaceholder: "E.g.: The Eiffel Tower, the Louvre museum...",
        durationLabel: "Discussion duration",
        durationQuick: "Short (~2 min)",
        durationMedium: "Medium (~4-5 min)",
        durationLong: "Long (~8 min)",
        button: "Generate story",
        buttonLoading: "Generating...",
        welcomeMessage: "Tell me what you'd like to explore, and I'll create a story for your trip!",
        errorPrefix: "An error occurred: ",
        copy: "Copy",
        copied: "Copied!",
        playAudio: "Play Audio",
        pauseAudio: "Pause",
        audioLoading: "Loading...",
        audioErrorPrefix: "Audio error: ",
        download: "Download",
        sourcesTitle: "Sources"
    }
};